### DISCUSSION TITLE
How to intergrate with Codegen?

### DISCUSSION THREAD

**Discussion by Zxilly** [Urigo/graphql-scalars#1181] [Q&A] [answered]
I noticed https://github.com/Urigo/graphql-scalars/commit/b217d0dc22f2c2212f50758b9684e68ab0eee612 adds support for codegen, but i have no idea about how to apply it to codegen.
Is there any document explains this?

**Comment by ardatan** [comment, marked as answer]
It automatically gets the TypeScript types so you don't need to do anything else.
> If you point your schema's code file like `schema.ts`, it will automatically inherit the TS types.
But still we recommend to use `scalars` configuration option in codegen.

**Reply by Zxilly** [reply]
But I still got `any` in generated files. All the packages have been latest.
This is my codegen.yml
```
overwrite: true
schema:
  - "./src/schemas/ref/*.graphql"
  - "./src/schemas/schema/*.graphql"
require:
  - ts-node/register
generates:
  src/generated/graphql.ts:
    config:
      useIndexSignature: true
    plugins:
      - "typescript"
      - "typescript-resolvers"
      - "typescript-document-nodes"
  ./graphql.schema.json:
    plugins:
      - "introspection"
```

Here's what I got after generate.
![image](https://user-images.githubusercontent.com/31370133/139917939-42ae017a-31e6-43b9-a7fd-118190e9e26d.png)

`ref` folder contains what i got from
```
import { typeDefs } from 'graphql-scalars';
import { parse } from 'graphql';

console.log(parse(typeDefs.join('\n')));
```
without this, I will got a
![image](https://user-images.githubusercontent.com/31370133/139918227-4ba705c8-e5c7-4653-aa93-eb481f6659c9.png)
